config/routes.rb
Clonyn::Application.routes.draw do
  get "profiles/show"

    
  
    as :user do
      get '/register', to: 'devise/registrations#new', as: :register
      get '/login', to: 'devise/sessions#new', as: :login
      get '/logout', to: 'devise/sessions#destroy', as: :logout
    end
  
    devise_for :users, skip: [:sessions]
    
    as :user do 
      get "/login" => 'devise/sessions#new', as: :new_user_session
      post "/login" => 'devise/sessions#create', as: :user_session
      delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
    end
  
  
  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end
  
  
  resources :statuses, :users
  get 'feed', to: 'statuses#index', as: :feed
  get '/host', to: 'host#index', as: 'host'
  root to: 'statuses#index'
  
  
  get '/:id', to: 'profiles#show', as: 'profile'
  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clonyn</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            
            <div class="container">
                <ul class="nav">
                    <!-- <a href="#" class="brand">Clonyn</a> -->
                    <li><%= link_to "Ticket Queue", feed_path %></li>
                </ul>
                <ul class="nav pull-right">
                    <% if user_signed_in? %>
                        <li><%= link_to "Host", '/host' %> </li>
                        <li><%= link_to 'Friends', user_friendships_path %></li>
                        <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
                        <li><%= link_to "Log out", logout_path %> </li>
                    <% else %>
                        <li><%= link_to "Register", register_path %></li>
                        <li><%= link_to "Log in", login_path %></li>
                        
                    <% end %>    
                </ul>
            </div>
        </div>
    </div>
    <div class="clonynlogo"><%= link_to image_tag('whitelogo.png', height: '30%', width: '30%', id: "img-responsive"), feed_path %></div>
    <div class="container">
        <% if signed_in? %>
        <h3>Instructions for Demonstration.</h3>
        <h5>User: Log a Support Ticket and monitor your "Friends" list for requests from Freelancers.</h5>
        <h5>Freelancer: Review the Support Tickets, click on the Users avatar and request friendship. Monitor your "Friends" list until accepted.</h5>
        <h5>User: Once accepted, follow the on-screen instructions to enter the Support Queue.</h5>
        <h5>Freelancer: Once accepted, go to the "Host" page and Join the session.</h5>
        <% end %>
            <% flash.each do |type, message| %>
            <div class="alert <%= flash_class type %>">
                <button class="close" data-dismiss="alert">x</button>
                <%= message %>
            </div>
            <% end %>
            
        <%= yield %>
    </div>
    
</body>
</html>